# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9da7ce637c6342bdfc6a000b0cdb4b96e00ffbe5ae6b1d12e073485412524056ca735c9262ecf5f12f9b93f10759939dd599a460537320dd1af1f68534f7dfe

test:
  secret_key_base: 02fa0f6a2dfb8ed82efd9ed09e7cc101024ed2ad7282ab5f0bf808aa9068061c427258b3cec24a66f8a1db5cac3f08257af3d53427b1c918234197d743e12d29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
